# Generated by Django 4.2.4 on 2023-10-10 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='comepleted',
            new_name='completed',
        ),
    ]
