# Generated by Django 4.2.4 on 2023-10-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_review_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
