# Generated by Django 4.2.4 on 2023-10-20 18:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=15)),
                ('login_time', models.DateTimeField(default=datetime.datetime.now)),
                ('login_success', models.BooleanField()),
                ('details', models.TextField(blank=True, max_length=2047, null=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'log',
            },
        ),
    ]
