# Generated by Django 4.2.4 on 2023-11-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('owner', 'Owner'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
